[package]
name = "termicall-shared"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
bincode.workspace = true
rand.workspace = true
bytes.workspace = true
anyhow.workspace = true
